### PR TITLE
feat(page): Login Page with Test cases

### PR DESCRIPTION
**Pull request by shubham-cpp**
login page changes

resolve alias

sample tests

chore(workflow): update tests.yml to include lint

tests for invalid states

### CODE REVIEW

**Comment by shubham-cpp** [comment]
Hi @azrael3199, Check for the theme stuff rest is working as expected

**Comment by azrael3199** [comment]
> Hi @azrael3199, Check for the theme stuff rest is working as expected

Oh yeah, I found the problem, I forgot to `extendTheme` the theme object before setting it to the Provider

**Comment by shubham-cpp** [comment]
So we're good to close this PR?

**Comment by azrael3199** [comment]
@shubham-cpp probably we can close it. But I was thinking maybe we could add the styling similar to the UX that we finalized in the same PR.

**Comment by azrael3199** [comment]
I wouldn't get time to do that today though, I will have to pick it up tomorrow

**Comment by shubham-cpp** [comment]
Styling we can prioritise it later. Yes styling is important but I would rather focus on functionality first than worry about the looks

**Comment by azrael3199** [comment]
> Styling we can prioritise it later. Yes styling is important but I would rather focus on functionality first than worry about the looks

Then I suppose we can merge this

**Review by azrael3199 — APPROVED** [review]

**Pull request merged**
